import React from 'react'

export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div> about page</div>
  )
}

export default page