import Navbar from "@/components/navbar";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ProviderRedux from "./provider";
import ReduxProvider from "@/redux/ReduxProvider";
import UserMessage from "./UserMessage";
import { Toaster } from "@/components/ui/sonner";



export const metadata = {
  title: "JobPortal Desi-Destination",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
            <Toaster richColors position="top-right" closeButton />
            <UserMessage />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
